### ISSUE TITLE
Unable to retrieve hebrew error messages

### ISSUE THREAD

**Issue by ybelenko** [dofinity/pelecard#10]
Official manual contains _Appendix B – Error Code List_ section. It seems to me that Pelecard API returns only english error messages even when payment page has been configured with hebrew locale.

### Suggested solution

Hardcode hebrew error messages from official manual into external PHP class. I can submit PR, it's almost ready if nobody have other ideas.

My implementation looks like:
```php
use Pelecard\PelecardPaymentStatus;

$status = new PelecardPaymentStatus('010', 'he');
$status->getMessage();
// output:
// תוכנית הופסקה עפ"י הוראת המפעיל (ESC) או COM PORT לא ניתן לפתיחה (WINDOWS).
```

**Comment by reissr** [comment]
I think that we have the full mapping of the error messages from En to He.
I'll check and send an update.
